#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TestTask.UI.Droid.Resource", IsApplication=true)]

namespace TestTask.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TestTask.Plugins.Pictures.Droid.Resource.String.library_name = global::TestTask.UI.Droid.Resource.String.library_name;
			global::TestTask.Plugins.Notifications.Droid.Resource.Id.MessageText = global::TestTask.UI.Droid.Resource.Id.MessageText;
			global::TestTask.Plugins.Notifications.Droid.Resource.Layout.ToastLayout = global::TestTask.UI.Droid.Resource.Layout.ToastLayout;
			global::TestTask.Plugins.Notifications.Droid.Resource.String.library_name = global::TestTask.UI.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int MvxDropDownItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int MvxItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int MvxSource = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checkbox_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int kitten = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int search_icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int MessageText = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int MyButton = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int coolPictureImageView = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int editText1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int entitesView = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int flipHorButton = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int flipVertButton = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int imgListView = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int imgView = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int lstContacts = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int progress = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int rotateButton = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int showPictureImageView = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactsView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CoolPictureView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditPictureView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EmailView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EntitiesView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EntityEditView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GrandView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListItem_contact = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListItem_entity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ListItem_kitten = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PicturesView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ShowPictureView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SplashScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ToastLayout = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxImageView = new int[]
			{
					2130771972};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
